{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "RUN.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "JmjNHVQzsebG",
        "colab_type": "code",
        "outputId": "fbfb632f-2fc8-4bdb-d26a-ba5306e0342f",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 34
        }
      },
      "source": [
        "!pip install import_ipynb"
      ],
      "execution_count": 3,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: import_ipynb in /usr/local/lib/python3.6/dist-packages (0.1.3)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "BW_X2kAh575F",
        "colab_type": "code",
        "outputId": "9f41252b-fe31-4fd3-d193-d2a26e65c550",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 334
        }
      },
      "source": [
        "import import_ipynb\n",
        "import data_builder\n",
        "import model_builder\n",
        "import matplotlib\n",
        "matplotlib.use(\"Agg\")\n",
        "from sklearn.preprocessing import LabelBinarizer\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.metrics import classification_report\n",
        "from keras.preprocessing.image import ImageDataGenerator\n",
        "from keras.optimizers import Adam\n",
        "from keras.regularizers import l2\n",
        "from keras.utils.np_utils import to_categorical\n",
        "from imutils import paths\n",
        "import matplotlib.pyplot as plt\n",
        "import tensorflow \n",
        "import pickle \n",
        "import numpy as np\n",
        "\n"
      ],
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "importing Jupyter notebook from data_builder.ipynb\n",
            "Collecting Pillow==5.3.0\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/62/94/5430ebaa83f91cc7a9f687ff5238e26164a779cca2ef9903232268b0a318/Pillow-5.3.0-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)\n",
            "\u001b[K     |████████████████████████████████| 2.0MB 3.2MB/s \n",
            "\u001b[31mERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: Pillow\n",
            "  Found existing installation: Pillow 7.0.0\n",
            "    Uninstalling Pillow-7.0.0:\n",
            "      Successfully uninstalled Pillow-7.0.0\n",
            "Successfully installed Pillow-5.3.0\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "display_data",
          "data": {
            "application/vnd.colab-display-data+json": {
              "pip_warning": {
                "packages": [
                  "PIL"
                ]
              }
            }
          },
          "metadata": {
            "tags": []
          }
        },
        {
          "output_type": "stream",
          "text": [
            "importing Jupyter notebook from model_builder.ipynb\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "Using TensorFlow backend.\n"
          ],
          "name": "stderr"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "GZEYGMhTszgO",
        "colab_type": "code",
        "outputId": "cd1c2da2-a206-4170-ffd3-5c7b40f015fe",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        }
      },
      "source": [
        "\n",
        "fights_video = \"/content/drive/My Drive/code/Peliculas/fights_video\"\n",
        "fights_img = \"/content/fights_img\"\n",
        "noFights_img= \"/content/noFights_img\"\n",
        "noFights_video=\"/content/drive/My Drive/code/Peliculas/noFights_video\"\n",
        "data_dir = \"/content\"\n",
        "data_builder.save_img(fights_video, fights_img)\n",
        "data_builder.save_img(noFights_video, noFights_img)\n",
        "\n",
        "data_dir = \"/content\"\n",
        "\n",
        "data_builder.image_builder(data_dir)\n",
        " "
      ],
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Successfully created the directory /content/fights_img \n",
            "hada howa range len ta3 vid range(0, 188)\n",
            "vidéo N°  1 ========================================\n",
            "extract images  frome video number : 1\n",
            "vidéo N°  2 ========================================\n",
            "extract images  frome video number : 2\n",
            "vidéo N°  3 ========================================\n",
            "extract images  frome video number : 3\n",
            "vidéo N°  4 ========================================\n",
            "extract images  frome video number : 4\n",
            "vidéo N°  5 ========================================\n",
            "extract images  frome video number : 5\n",
            "vidéo N°  6 ========================================\n",
            "extract images  frome video number : 6\n",
            "vidéo N°  7 ========================================\n",
            "extract images  frome video number : 7\n",
            "vidéo N°  8 ========================================\n",
            "extract images  frome video number : 8\n",
            "vidéo N°  9 ========================================\n",
            "extract images  frome video number : 9\n",
            "vidéo N°  10 ========================================\n",
            "extract images  frome video number : 10\n",
            "vidéo N°  11 ========================================\n",
            "extract images  frome video number : 11\n",
            "vidéo N°  12 ========================================\n",
            "extract images  frome video number : 12\n",
            "vidéo N°  13 ========================================\n",
            "extract images  frome video number : 13\n",
            "vidéo N°  14 ========================================\n",
            "extract images  frome video number : 14\n",
            "vidéo N°  15 ========================================\n",
            "extract images  frome video number : 15\n",
            "vidéo N°  16 ========================================\n",
            "extract images  frome video number : 16\n",
            "vidéo N°  17 ========================================\n",
            "extract images  frome video number : 17\n",
            "vidéo N°  18 ========================================\n",
            "extract images  frome video number : 18\n",
            "vidéo N°  19 ========================================\n",
            "extract images  frome video number : 19\n",
            "vidéo N°  20 ========================================\n",
            "extract images  frome video number : 20\n",
            "vidéo N°  21 ========================================\n",
            "extract images  frome video number : 21\n",
            "vidéo N°  22 ========================================\n",
            "extract images  frome video number : 22\n",
            "vidéo N°  23 ========================================\n",
            "extract images  frome video number : 23\n",
            "vidéo N°  24 ========================================\n",
            "extract images  frome video number : 24\n",
            "vidéo N°  25 ========================================\n",
            "extract images  frome video number : 25\n",
            "vidéo N°  26 ========================================\n",
            "extract images  frome video number : 26\n",
            "vidéo N°  27 ========================================\n",
            "extract images  frome video number : 27\n",
            "vidéo N°  28 ========================================\n",
            "extract images  frome video number : 28\n",
            "vidéo N°  29 ========================================\n",
            "extract images  frome video number : 29\n",
            "vidéo N°  30 ========================================\n",
            "extract images  frome video number : 30\n",
            "vidéo N°  31 ========================================\n",
            "extract images  frome video number : 31\n",
            "vidéo N°  32 ========================================\n",
            "extract images  frome video number : 32\n",
            "vidéo N°  33 ========================================\n",
            "extract images  frome video number : 33\n",
            "vidéo N°  34 ========================================\n",
            "extract images  frome video number : 34\n",
            "vidéo N°  35 ========================================\n",
            "extract images  frome video number : 35\n",
            "vidéo N°  36 ========================================\n",
            "extract images  frome video number : 36\n",
            "vidéo N°  37 ========================================\n",
            "extract images  frome video number : 37\n",
            "vidéo N°  38 ========================================\n",
            "extract images  frome video number : 38\n",
            "vidéo N°  39 ========================================\n",
            "extract images  frome video number : 39\n",
            "vidéo N°  40 ========================================\n",
            "extract images  frome video number : 40\n",
            "vidéo N°  41 ========================================\n",
            "extract images  frome video number : 41\n",
            "vidéo N°  42 ========================================\n",
            "extract images  frome video number : 42\n",
            "vidéo N°  43 ========================================\n",
            "extract images  frome video number : 43\n",
            "vidéo N°  44 ========================================\n",
            "extract images  frome video number : 44\n",
            "vidéo N°  45 ========================================\n",
            "extract images  frome video number : 45\n",
            "vidéo N°  46 ========================================\n",
            "extract images  frome video number : 46\n",
            "vidéo N°  47 ========================================\n",
            "extract images  frome video number : 47\n",
            "vidéo N°  48 ========================================\n",
            "extract images  frome video number : 48\n",
            "vidéo N°  49 ========================================\n",
            "extract images  frome video number : 49\n",
            "vidéo N°  50 ========================================\n",
            "extract images  frome video number : 50\n",
            "vidéo N°  51 ========================================\n",
            "extract images  frome video number : 51\n",
            "vidéo N°  52 ========================================\n",
            "extract images  frome video number : 52\n",
            "vidéo N°  53 ========================================\n",
            "extract images  frome video number : 53\n",
            "vidéo N°  54 ========================================\n",
            "extract images  frome video number : 54\n",
            "vidéo N°  55 ========================================\n",
            "extract images  frome video number : 55\n",
            "vidéo N°  56 ========================================\n",
            "extract images  frome video number : 56\n",
            "vidéo N°  57 ========================================\n",
            "extract images  frome video number : 57\n",
            "vidéo N°  58 ========================================\n",
            "extract images  frome video number : 58\n",
            "vidéo N°  59 ========================================\n",
            "extract images  frome video number : 59\n",
            "vidéo N°  60 ========================================\n",
            "extract images  frome video number : 60\n",
            "vidéo N°  61 ========================================\n",
            "extract images  frome video number : 61\n",
            "vidéo N°  62 ========================================\n",
            "extract images  frome video number : 62\n",
            "vidéo N°  63 ========================================\n",
            "extract images  frome video number : 63\n",
            "vidéo N°  64 ========================================\n",
            "extract images  frome video number : 64\n",
            "vidéo N°  65 ========================================\n",
            "extract images  frome video number : 65\n",
            "vidéo N°  66 ========================================\n",
            "extract images  frome video number : 66\n",
            "vidéo N°  67 ========================================\n",
            "extract images  frome video number : 67\n",
            "vidéo N°  68 ========================================\n",
            "extract images  frome video number : 68\n",
            "vidéo N°  69 ========================================\n",
            "extract images  frome video number : 69\n",
            "vidéo N°  70 ========================================\n",
            "extract images  frome video number : 70\n",
            "vidéo N°  71 ========================================\n",
            "extract images  frome video number : 71\n",
            "vidéo N°  72 ========================================\n",
            "extract images  frome video number : 72\n",
            "vidéo N°  73 ========================================\n",
            "extract images  frome video number : 73\n",
            "vidéo N°  74 ========================================\n",
            "extract images  frome video number : 74\n",
            "vidéo N°  75 ========================================\n",
            "extract images  frome video number : 75\n",
            "vidéo N°  76 ========================================\n",
            "extract images  frome video number : 76\n",
            "vidéo N°  77 ========================================\n",
            "extract images  frome video number : 77\n",
            "vidéo N°  78 ========================================\n",
            "extract images  frome video number : 78\n",
            "vidéo N°  79 ========================================\n",
            "extract images  frome video number : 79\n",
            "vidéo N°  80 ========================================\n",
            "extract images  frome video number : 80\n",
            "vidéo N°  81 ========================================\n",
            "extract images  frome video number : 81\n",
            "vidéo N°  82 ========================================\n",
            "extract images  frome video number : 82\n",
            "vidéo N°  83 ========================================\n",
            "extract images  frome video number : 83\n",
            "vidéo N°  84 ========================================\n",
            "extract images  frome video number : 84\n",
            "vidéo N°  85 ========================================\n",
            "extract images  frome video number : 85\n",
            "vidéo N°  86 ========================================\n",
            "extract images  frome video number : 86\n",
            "vidéo N°  87 ========================================\n",
            "extract images  frome video number : 87\n",
            "vidéo N°  88 ========================================\n",
            "extract images  frome video number : 88\n",
            "vidéo N°  89 ========================================\n",
            "extract images  frome video number : 89\n",
            "vidéo N°  90 ========================================\n",
            "extract images  frome video number : 90\n",
            "vidéo N°  91 ========================================\n",
            "extract images  frome video number : 91\n",
            "vidéo N°  92 ========================================\n",
            "extract images  frome video number : 92\n",
            "vidéo N°  93 ========================================\n",
            "extract images  frome video number : 93\n",
            "vidéo N°  94 ========================================\n",
            "extract images  frome video number : 94\n",
            "vidéo N°  95 ========================================\n",
            "extract images  frome video number : 95\n",
            "vidéo N°  96 ========================================\n",
            "extract images  frome video number : 96\n",
            "vidéo N°  97 ========================================\n",
            "extract images  frome video number : 97\n",
            "vidéo N°  98 ========================================\n",
            "extract images  frome video number : 98\n",
            "vidéo N°  99 ========================================\n",
            "extract images  frome video number : 99\n",
            "vidéo N°  100 ========================================\n",
            "extract images  frome video number : 100\n",
            "vidéo N°  101 ========================================\n",
            "extract images  frome video number : 101\n",
            "vidéo N°  102 ========================================\n",
            "extract images  frome video number : 102\n",
            "vidéo N°  103 ========================================\n",
            "extract images  frome video number : 103\n",
            "vidéo N°  104 ========================================\n",
            "extract images  frome video number : 104\n",
            "vidéo N°  105 ========================================\n",
            "extract images  frome video number : 105\n",
            "vidéo N°  106 ========================================\n",
            "extract images  frome video number : 106\n",
            "vidéo N°  107 ========================================\n",
            "extract images  frome video number : 107\n",
            "vidéo N°  108 ========================================\n",
            "extract images  frome video number : 108\n",
            "vidéo N°  109 ========================================\n",
            "extract images  frome video number : 109\n",
            "vidéo N°  110 ========================================\n",
            "extract images  frome video number : 110\n",
            "vidéo N°  111 ========================================\n",
            "extract images  frome video number : 111\n",
            "vidéo N°  112 ========================================\n",
            "extract images  frome video number : 112\n",
            "vidéo N°  113 ========================================\n",
            "extract images  frome video number : 113\n",
            "vidéo N°  114 ========================================\n",
            "extract images  frome video number : 114\n",
            "vidéo N°  115 ========================================\n",
            "extract images  frome video number : 115\n",
            "vidéo N°  116 ========================================\n",
            "extract images  frome video number : 116\n",
            "vidéo N°  117 ========================================\n",
            "extract images  frome video number : 117\n",
            "vidéo N°  118 ========================================\n",
            "extract images  frome video number : 118\n",
            "vidéo N°  119 ========================================\n",
            "extract images  frome video number : 119\n",
            "vidéo N°  120 ========================================\n",
            "extract images  frome video number : 120\n",
            "vidéo N°  121 ========================================\n",
            "extract images  frome video number : 121\n",
            "vidéo N°  122 ========================================\n",
            "extract images  frome video number : 122\n",
            "vidéo N°  123 ========================================\n",
            "extract images  frome video number : 123\n",
            "vidéo N°  124 ========================================\n",
            "extract images  frome video number : 124\n",
            "vidéo N°  125 ========================================\n",
            "extract images  frome video number : 125\n",
            "vidéo N°  126 ========================================\n",
            "extract images  frome video number : 126\n",
            "vidéo N°  127 ========================================\n",
            "extract images  frome video number : 127\n",
            "vidéo N°  128 ========================================\n",
            "extract images  frome video number : 128\n",
            "vidéo N°  129 ========================================\n",
            "extract images  frome video number : 129\n",
            "vidéo N°  130 ========================================\n",
            "extract images  frome video number : 130\n",
            "vidéo N°  131 ========================================\n",
            "extract images  frome video number : 131\n",
            "vidéo N°  132 ========================================\n",
            "extract images  frome video number : 132\n",
            "vidéo N°  133 ========================================\n",
            "extract images  frome video number : 133\n",
            "vidéo N°  134 ========================================\n",
            "extract images  frome video number : 134\n",
            "vidéo N°  135 ========================================\n",
            "extract images  frome video number : 135\n",
            "vidéo N°  136 ========================================\n",
            "extract images  frome video number : 136\n",
            "vidéo N°  137 ========================================\n",
            "extract images  frome video number : 137\n",
            "vidéo N°  138 ========================================\n",
            "extract images  frome video number : 138\n",
            "vidéo N°  139 ========================================\n",
            "extract images  frome video number : 139\n",
            "vidéo N°  140 ========================================\n",
            "extract images  frome video number : 140\n",
            "vidéo N°  141 ========================================\n",
            "extract images  frome video number : 141\n",
            "vidéo N°  142 ========================================\n",
            "extract images  frome video number : 142\n",
            "vidéo N°  143 ========================================\n",
            "extract images  frome video number : 143\n",
            "vidéo N°  144 ========================================\n",
            "extract images  frome video number : 144\n",
            "vidéo N°  145 ========================================\n",
            "extract images  frome video number : 145\n",
            "vidéo N°  146 ========================================\n",
            "extract images  frome video number : 146\n",
            "vidéo N°  147 ========================================\n",
            "extract images  frome video number : 147\n",
            "vidéo N°  148 ========================================\n",
            "extract images  frome video number : 148\n",
            "vidéo N°  149 ========================================\n",
            "extract images  frome video number : 149\n",
            "vidéo N°  150 ========================================\n",
            "extract images  frome video number : 150\n",
            "vidéo N°  151 ========================================\n",
            "extract images  frome video number : 151\n",
            "vidéo N°  152 ========================================\n",
            "extract images  frome video number : 152\n",
            "vidéo N°  153 ========================================\n",
            "extract images  frome video number : 153\n",
            "vidéo N°  154 ========================================\n",
            "extract images  frome video number : 154\n",
            "vidéo N°  155 ========================================\n",
            "extract images  frome video number : 155\n",
            "vidéo N°  156 ========================================\n",
            "extract images  frome video number : 156\n",
            "vidéo N°  157 ========================================\n",
            "extract images  frome video number : 157\n",
            "vidéo N°  158 ========================================\n",
            "extract images  frome video number : 158\n",
            "vidéo N°  159 ========================================\n",
            "extract images  frome video number : 159\n",
            "vidéo N°  160 ========================================\n",
            "extract images  frome video number : 160\n",
            "vidéo N°  161 ========================================\n",
            "extract images  frome video number : 161\n",
            "vidéo N°  162 ========================================\n",
            "extract images  frome video number : 162\n",
            "vidéo N°  163 ========================================\n",
            "extract images  frome video number : 163\n",
            "vidéo N°  164 ========================================\n",
            "extract images  frome video number : 164\n",
            "vidéo N°  165 ========================================\n",
            "extract images  frome video number : 165\n",
            "vidéo N°  166 ========================================\n",
            "extract images  frome video number : 166\n",
            "vidéo N°  167 ========================================\n",
            "extract images  frome video number : 167\n",
            "vidéo N°  168 ========================================\n",
            "extract images  frome video number : 168\n",
            "vidéo N°  169 ========================================\n",
            "extract images  frome video number : 169\n",
            "vidéo N°  170 ========================================\n",
            "extract images  frome video number : 170\n",
            "vidéo N°  171 ========================================\n",
            "extract images  frome video number : 171\n",
            "vidéo N°  172 ========================================\n",
            "extract images  frome video number : 172\n",
            "vidéo N°  173 ========================================\n",
            "extract images  frome video number : 173\n",
            "vidéo N°  174 ========================================\n",
            "extract images  frome video number : 174\n",
            "vidéo N°  175 ========================================\n",
            "extract images  frome video number : 175\n",
            "vidéo N°  176 ========================================\n",
            "extract images  frome video number : 176\n",
            "vidéo N°  177 ========================================\n",
            "extract images  frome video number : 177\n",
            "vidéo N°  178 ========================================\n",
            "extract images  frome video number : 178\n",
            "vidéo N°  179 ========================================\n",
            "extract images  frome video number : 179\n",
            "vidéo N°  180 ========================================\n",
            "extract images  frome video number : 180\n",
            "vidéo N°  181 ========================================\n",
            "extract images  frome video number : 181\n",
            "vidéo N°  182 ========================================\n",
            "extract images  frome video number : 182\n",
            "vidéo N°  183 ========================================\n",
            "extract images  frome video number : 183\n",
            "vidéo N°  184 ========================================\n",
            "extract images  frome video number : 184\n",
            "vidéo N°  185 ========================================\n",
            "extract images  frome video number : 185\n",
            "vidéo N°  186 ========================================\n",
            "extract images  frome video number : 186\n",
            "vidéo N°  187 ========================================\n",
            "extract images  frome video number : 187\n",
            "vidéo N°  188 ========================================\n",
            "extract images  frome video number : 188\n",
            "Successfully created the directory /content/noFights_img \n",
            "hada howa range len ta3 vid range(0, 128)\n",
            "vidéo N°  1 ========================================\n",
            "extract images  frome video number : 1\n",
            "vidéo N°  2 ========================================\n",
            "extract images  frome video number : 2\n",
            "vidéo N°  3 ========================================\n",
            "extract images  frome video number : 3\n",
            "vidéo N°  4 ========================================\n",
            "extract images  frome video number : 4\n",
            "vidéo N°  5 ========================================\n",
            "extract images  frome video number : 5\n",
            "vidéo N°  6 ========================================\n",
            "extract images  frome video number : 6\n",
            "vidéo N°  7 ========================================\n",
            "extract images  frome video number : 7\n",
            "vidéo N°  8 ========================================\n",
            "extract images  frome video number : 8\n",
            "vidéo N°  9 ========================================\n",
            "extract images  frome video number : 9\n",
            "vidéo N°  10 ========================================\n",
            "extract images  frome video number : 10\n",
            "vidéo N°  11 ========================================\n",
            "extract images  frome video number : 11\n",
            "vidéo N°  12 ========================================\n",
            "extract images  frome video number : 12\n",
            "vidéo N°  13 ========================================\n",
            "extract images  frome video number : 13\n",
            "vidéo N°  14 ========================================\n",
            "extract images  frome video number : 14\n",
            "vidéo N°  15 ========================================\n",
            "extract images  frome video number : 15\n",
            "vidéo N°  16 ========================================\n",
            "extract images  frome video number : 16\n",
            "vidéo N°  17 ========================================\n",
            "extract images  frome video number : 17\n",
            "vidéo N°  18 ========================================\n",
            "extract images  frome video number : 18\n",
            "vidéo N°  19 ========================================\n",
            "extract images  frome video number : 19\n",
            "vidéo N°  20 ========================================\n",
            "extract images  frome video number : 20\n",
            "vidéo N°  21 ========================================\n",
            "extract images  frome video number : 21\n",
            "vidéo N°  22 ========================================\n",
            "extract images  frome video number : 22\n",
            "vidéo N°  23 ========================================\n",
            "extract images  frome video number : 23\n",
            "vidéo N°  24 ========================================\n",
            "extract images  frome video number : 24\n",
            "vidéo N°  25 ========================================\n",
            "extract images  frome video number : 25\n",
            "vidéo N°  26 ========================================\n",
            "extract images  frome video number : 26\n",
            "vidéo N°  27 ========================================\n",
            "extract images  frome video number : 27\n",
            "vidéo N°  28 ========================================\n",
            "extract images  frome video number : 28\n",
            "vidéo N°  29 ========================================\n",
            "extract images  frome video number : 29\n",
            "vidéo N°  30 ========================================\n",
            "extract images  frome video number : 30\n",
            "vidéo N°  31 ========================================\n",
            "extract images  frome video number : 31\n",
            "vidéo N°  32 ========================================\n",
            "extract images  frome video number : 32\n",
            "vidéo N°  33 ========================================\n",
            "extract images  frome video number : 33\n",
            "vidéo N°  34 ========================================\n",
            "extract images  frome video number : 34\n",
            "vidéo N°  35 ========================================\n",
            "extract images  frome video number : 35\n",
            "vidéo N°  36 ========================================\n",
            "extract images  frome video number : 36\n",
            "vidéo N°  37 ========================================\n",
            "extract images  frome video number : 37\n",
            "vidéo N°  38 ========================================\n",
            "extract images  frome video number : 38\n",
            "vidéo N°  39 ========================================\n",
            "extract images  frome video number : 39\n",
            "vidéo N°  40 ========================================\n",
            "extract images  frome video number : 40\n",
            "vidéo N°  41 ========================================\n",
            "extract images  frome video number : 41\n",
            "vidéo N°  42 ========================================\n",
            "extract images  frome video number : 42\n",
            "vidéo N°  43 ========================================\n",
            "extract images  frome video number : 43\n",
            "vidéo N°  44 ========================================\n",
            "extract images  frome video number : 44\n",
            "vidéo N°  45 ========================================\n",
            "extract images  frome video number : 45\n",
            "vidéo N°  46 ========================================\n",
            "extract images  frome video number : 46\n",
            "vidéo N°  47 ========================================\n",
            "extract images  frome video number : 47\n",
            "vidéo N°  48 ========================================\n",
            "extract images  frome video number : 48\n",
            "vidéo N°  49 ========================================\n",
            "extract images  frome video number : 49\n",
            "vidéo N°  50 ========================================\n",
            "extract images  frome video number : 50\n",
            "vidéo N°  51 ========================================\n",
            "extract images  frome video number : 51\n",
            "vidéo N°  52 ========================================\n",
            "extract images  frome video number : 52\n",
            "vidéo N°  53 ========================================\n",
            "extract images  frome video number : 53\n",
            "vidéo N°  54 ========================================\n",
            "extract images  frome video number : 54\n",
            "vidéo N°  55 ========================================\n",
            "extract images  frome video number : 55\n",
            "vidéo N°  56 ========================================\n",
            "extract images  frome video number : 56\n",
            "vidéo N°  57 ========================================\n",
            "extract images  frome video number : 57\n",
            "vidéo N°  58 ========================================\n",
            "extract images  frome video number : 58\n",
            "vidéo N°  59 ========================================\n",
            "extract images  frome video number : 59\n",
            "vidéo N°  60 ========================================\n",
            "extract images  frome video number : 60\n",
            "vidéo N°  61 ========================================\n",
            "extract images  frome video number : 61\n",
            "vidéo N°  62 ========================================\n",
            "extract images  frome video number : 62\n",
            "vidéo N°  63 ========================================\n",
            "extract images  frome video number : 63\n",
            "vidéo N°  64 ========================================\n",
            "extract images  frome video number : 64\n",
            "vidéo N°  65 ========================================\n",
            "extract images  frome video number : 65\n",
            "vidéo N°  66 ========================================\n",
            "extract images  frome video number : 66\n",
            "vidéo N°  67 ========================================\n",
            "extract images  frome video number : 67\n",
            "vidéo N°  68 ========================================\n",
            "extract images  frome video number : 68\n",
            "vidéo N°  69 ========================================\n",
            "extract images  frome video number : 69\n",
            "vidéo N°  70 ========================================\n",
            "extract images  frome video number : 70\n",
            "vidéo N°  71 ========================================\n",
            "extract images  frome video number : 71\n",
            "vidéo N°  72 ========================================\n",
            "extract images  frome video number : 72\n",
            "vidéo N°  73 ========================================\n",
            "extract images  frome video number : 73\n",
            "vidéo N°  74 ========================================\n",
            "extract images  frome video number : 74\n",
            "vidéo N°  75 ========================================\n",
            "extract images  frome video number : 75\n",
            "vidéo N°  76 ========================================\n",
            "extract images  frome video number : 76\n",
            "vidéo N°  77 ========================================\n",
            "extract images  frome video number : 77\n",
            "vidéo N°  78 ========================================\n",
            "extract images  frome video number : 78\n",
            "vidéo N°  79 ========================================\n",
            "extract images  frome video number : 79\n",
            "vidéo N°  80 ========================================\n",
            "extract images  frome video number : 80\n",
            "vidéo N°  81 ========================================\n",
            "extract images  frome video number : 81\n",
            "vidéo N°  82 ========================================\n",
            "extract images  frome video number : 82\n",
            "vidéo N°  83 ========================================\n",
            "extract images  frome video number : 83\n",
            "vidéo N°  84 ========================================\n",
            "extract images  frome video number : 84\n",
            "vidéo N°  85 ========================================\n",
            "extract images  frome video number : 85\n",
            "vidéo N°  86 ========================================\n",
            "extract images  frome video number : 86\n",
            "vidéo N°  87 ========================================\n",
            "extract images  frome video number : 87\n",
            "vidéo N°  88 ========================================\n",
            "extract images  frome video number : 88\n",
            "vidéo N°  89 ========================================\n",
            "extract images  frome video number : 89\n",
            "vidéo N°  90 ========================================\n",
            "extract images  frome video number : 90\n",
            "vidéo N°  91 ========================================\n",
            "extract images  frome video number : 91\n",
            "vidéo N°  92 ========================================\n",
            "extract images  frome video number : 92\n",
            "vidéo N°  93 ========================================\n",
            "extract images  frome video number : 93\n",
            "vidéo N°  94 ========================================\n",
            "extract images  frome video number : 94\n",
            "vidéo N°  95 ========================================\n",
            "extract images  frome video number : 95\n",
            "vidéo N°  96 ========================================\n",
            "extract images  frome video number : 96\n",
            "vidéo N°  97 ========================================\n",
            "extract images  frome video number : 97\n",
            "vidéo N°  98 ========================================\n",
            "extract images  frome video number : 98\n",
            "vidéo N°  99 ========================================\n",
            "extract images  frome video number : 99\n",
            "vidéo N°  100 ========================================\n",
            "extract images  frome video number : 100\n",
            "vidéo N°  101 ========================================\n",
            "extract images  frome video number : 101\n",
            "vidéo N°  102 ========================================\n",
            "extract images  frome video number : 102\n",
            "vidéo N°  103 ========================================\n",
            "extract images  frome video number : 103\n",
            "vidéo N°  104 ========================================\n",
            "extract images  frome video number : 104\n",
            "vidéo N°  105 ========================================\n",
            "extract images  frome video number : 105\n",
            "vidéo N°  106 ========================================\n",
            "extract images  frome video number : 106\n",
            "vidéo N°  107 ========================================\n",
            "extract images  frome video number : 107\n",
            "vidéo N°  108 ========================================\n",
            "extract images  frome video number : 108\n",
            "vidéo N°  109 ========================================\n",
            "extract images  frome video number : 109\n",
            "vidéo N°  110 ========================================\n",
            "extract images  frome video number : 110\n",
            "vidéo N°  111 ========================================\n",
            "extract images  frome video number : 111\n",
            "vidéo N°  112 ========================================\n",
            "extract images  frome video number : 112\n",
            "vidéo N°  113 ========================================\n",
            "extract images  frome video number : 113\n",
            "vidéo N°  114 ========================================\n",
            "extract images  frome video number : 114\n",
            "vidéo N°  115 ========================================\n",
            "extract images  frome video number : 115\n",
            "vidéo N°  116 ========================================\n",
            "extract images  frome video number : 116\n",
            "vidéo N°  117 ========================================\n",
            "extract images  frome video number : 117\n",
            "vidéo N°  118 ========================================\n",
            "extract images  frome video number : 118\n",
            "vidéo N°  119 ========================================\n",
            "extract images  frome video number : 119\n",
            "vidéo N°  120 ========================================\n",
            "extract images  frome video number : 120\n",
            "vidéo N°  121 ========================================\n",
            "extract images  frome video number : 121\n",
            "vidéo N°  122 ========================================\n",
            "extract images  frome video number : 122\n",
            "vidéo N°  123 ========================================\n",
            "extract images  frome video number : 123\n",
            "vidéo N°  124 ========================================\n",
            "extract images  frome video number : 124\n",
            "vidéo N°  125 ========================================\n",
            "extract images  frome video number : 125\n",
            "vidéo N°  126 ========================================\n",
            "extract images  frome video number : 126\n",
            "vidéo N°  127 ========================================\n",
            "extract images  frome video number : 127\n",
            "vidéo N°  128 ========================================\n",
            "extract images  frome video number : 128\n",
            " start building data :\n",
            "pour le type  :  fights_img\n",
            "pour le type  :  noFights_img\n",
            "training data =  [[array([[ 13,  19,  22, ...,  29,  80,  85],\n",
            "       [ 17,  22,  37, ...,  27,  94,  89],\n",
            "       [ 66, 154,  73, ...,  39, 107,  94],\n",
            "       ...,\n",
            "       [ 10,  14,  24, ..., 161,  43,   9],\n",
            "       [  7,   4,  18, ..., 166,  90,  15],\n",
            "       [  6,   6,  10, ..., 161, 143,  18]], dtype=uint8), 'fights_img'], [array([[33, 35, 39, ..., 50, 47, 44],\n",
            "       [33, 35, 39, ..., 50, 47, 43],\n",
            "       [33, 35, 39, ..., 49, 46, 43],\n",
            "       ...,\n",
            "       [23, 24, 25, ..., 96, 95, 92],\n",
            "       [22, 23, 24, ..., 96, 95, 92],\n",
            "       [22, 23, 24, ..., 96, 95, 91]], dtype=uint8), 'noFights_img'], [array([[  0,   1,   0, ...,   0,   0,   0],\n",
            "       [  6,   3,   3, ...,  17,  16,   4],\n",
            "       [  5,   5,   5, ...,  17,  17,   2],\n",
            "       ...,\n",
            "       [ 76,  90, 104, ...,  68,  72,  33],\n",
            "       [ 87, 106, 114, ...,  70,  73,  32],\n",
            "       [  1,   1,   2, ...,   0,   0,   0]], dtype=uint8), 'fights_img'], [array([[  2,  60,  59, ...,  36,  15, 237],\n",
            "       [  2,  60,  60, ..., 255, 253, 246],\n",
            "       [  2,  60,  61, ...,  27, 121, 240],\n",
            "       ...,\n",
            "       [ 16, 161, 219, ..., 185, 186, 187],\n",
            "       [ 13,  46,  41, ..., 213, 212, 213],\n",
            "       [ 45, 128, 156, ...,  65,  65,  66]], dtype=uint8), 'fights_img'], [array([[ 0,  0,  0, ...,  0,  0,  0],\n",
            "       [ 0,  0,  0, ...,  0,  0,  0],\n",
            "       [ 0,  0,  0, ...,  0,  0,  0],\n",
            "       ...,\n",
            "       [ 0,  0, 81, ...,  8,  0,  0],\n",
            "       [ 0,  0, 79, ...,  7,  0,  0],\n",
            "       [ 0,  0, 24, ...,  1,  0,  0]], dtype=uint8), 'fights_img']]\n",
            "X =  [[[ 13  19  22 ...  29  80  85]\n",
            "  [ 17  22  37 ...  27  94  89]\n",
            "  [ 66 154  73 ...  39 107  94]\n",
            "  ...\n",
            "  [ 10  14  24 ... 161  43   9]\n",
            "  [  7   4  18 ... 166  90  15]\n",
            "  [  6   6  10 ... 161 143  18]]\n",
            "\n",
            " [[ 33  35  39 ...  50  47  44]\n",
            "  [ 33  35  39 ...  50  47  43]\n",
            "  [ 33  35  39 ...  49  46  43]\n",
            "  ...\n",
            "  [ 23  24  25 ...  96  95  92]\n",
            "  [ 22  23  24 ...  96  95  92]\n",
            "  [ 22  23  24 ...  96  95  91]]\n",
            "\n",
            " [[  0   1   0 ...   0   0   0]\n",
            "  [  6   3   3 ...  17  16   4]\n",
            "  [  5   5   5 ...  17  17   2]\n",
            "  ...\n",
            "  [ 76  90 104 ...  68  72  33]\n",
            "  [ 87 106 114 ...  70  73  32]\n",
            "  [  1   1   2 ...   0   0   0]]\n",
            "\n",
            " ...\n",
            "\n",
            " [[  0   0   0 ...   0   0   0]\n",
            "  [  0   0   0 ...   0   0   0]\n",
            "  [  0   0   0 ...   0   0   0]\n",
            "  ...\n",
            "  [  0   0   0 ...   0   0   0]\n",
            "  [  0   0   0 ...   0   0   0]\n",
            "  [  0   0   0 ...   0   0   0]]\n",
            "\n",
            " [[  0   0   0 ...   0   0   0]\n",
            "  [  0   0   0 ...   0   0   0]\n",
            "  [  0   0   0 ...   0   0   0]\n",
            "  ...\n",
            "  [  0   0   0 ...   0   0   0]\n",
            "  [  0   0   0 ...   0   0   0]\n",
            "  [  0   0   0 ...   0   0   0]]\n",
            "\n",
            " [[  0   0  44 ... 197   0   0]\n",
            "  [  0   0  31 ...  52   0   0]\n",
            "  [  0   0  18 ...  27   0   0]\n",
            "  ...\n",
            "  [  0   0  11 ... 147   0   0]\n",
            "  [  0   0  11 ... 149   0   0]\n",
            "  [  0   0  11 ... 114   0   0]]]\n",
            "save as pickle : \n",
            "save features was done :)\n",
            "save labels was done :)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "GmD-x7dPd1Qw",
        "colab_type": "code",
        "outputId": "da460fe5-b438-4f28-af89-5c094a8614ef",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 86
        }
      },
      "source": [
        "X = pickle.load(open(\"X.pickle\" , \"rb\"))\n",
        "Y = pickle.load(open(\"Y.pickle\" , 'rb'))\n",
        "y = np.array(Y)\n",
        "\n",
        "X = X/255.0 \n",
        "print(len(X))\n",
        "print(len(y))\n",
        "\n",
        "# partition the data into training and testing splits using 75% of\n",
        "# the data for training and the remaining 25% for testing\n",
        "(trainX, testX, trainY, testY) = train_test_split(X, Y,\n",
        "\ttest_size=0.25, stratify=Y, random_state=42)\n",
        "\n",
        "# construct the training image generator for data augmentation\n",
        "aug = ImageDataGenerator(rotation_range=20, zoom_range=0.15,\n",
        "\twidth_shift_range=0.2, height_shift_range=0.2, shear_range=0.15,\n",
        "\thorizontal_flip=True, fill_mode=\"nearest\")\n",
        "\n",
        "# initialize the optimizer and model\n",
        "print(\"[INFO] compiling model...\")\n",
        "epo = 60\n",
        "opt = Adam(lr=1e-4, decay=1e-4 / epo)\n",
        "\n",
        "lb = LabelBinarizer()\n",
        "trainY = lb.fit_transform(trainY)\n",
        "testY = lb.fit_transform(testY)\n",
        "print(trainX.shape)\n",
        "\n",
        "#build the model\n",
        "model = model_builder.StridedNet.build(width=160, height=160, depth=1,\n",
        "\tclasses= len(lb.classes_), reg=l2(0.0005))\n",
        "\n",
        "\n"
      ],
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "16790\n",
            "16790\n",
            "[INFO] compiling model...\n",
            "(12592, 160, 160)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "GVoPmTvkEitK",
        "colab_type": "code",
        "outputId": "cf524a31-d631-43ca-abc2-c2a51d73f67f",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 52
        }
      },
      "source": [
        "trainX = trainX.reshape(trainX.shape[0], trainX.shape[1], trainX.shape[2], 1)\n",
        "testX = testX.reshape(testX.shape[0], testX.shape[1], testX.shape[2], 1)\n",
        "\n",
        "print(trainX.shape)\n",
        "print(testX.shape)"
      ],
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "(12592, 160, 160, 1)\n",
            "(4198, 160, 160, 1)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "-FoaJGapH750",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        ""
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "6jVHC7SPJ6T8",
        "colab_type": "code",
        "outputId": "0216bce4-4d51-4ff8-c7db-0beeae4ee642",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        }
      },
      "source": [
        "model.compile(loss=\"binary_crossentropy\", optimizer=opt,\n",
        "\tmetrics=[\"accuracy\"])\n",
        "model.summary()"
      ],
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Model: \"sequential_1\"\n",
            "_________________________________________________________________\n",
            "Layer (type)                 Output Shape              Param #   \n",
            "=================================================================\n",
            "conv2d_1 (Conv2D)            (None, 77, 77, 16)        800       \n",
            "_________________________________________________________________\n",
            "conv2d_2 (Conv2D)            (None, 39, 39, 32)        4640      \n",
            "_________________________________________________________________\n",
            "activation_1 (Activation)    (None, 39, 39, 32)        0         \n",
            "_________________________________________________________________\n",
            "batch_normalization_1 (Batch (None, 39, 39, 32)        128       \n",
            "_________________________________________________________________\n",
            "conv2d_3 (Conv2D)            (None, 20, 20, 32)        9248      \n",
            "_________________________________________________________________\n",
            "activation_2 (Activation)    (None, 20, 20, 32)        0         \n",
            "_________________________________________________________________\n",
            "batch_normalization_2 (Batch (None, 20, 20, 32)        128       \n",
            "_________________________________________________________________\n",
            "dropout_1 (Dropout)          (None, 20, 20, 32)        0         \n",
            "_________________________________________________________________\n",
            "conv2d_4 (Conv2D)            (None, 10, 10, 64)        18496     \n",
            "_________________________________________________________________\n",
            "activation_3 (Activation)    (None, 10, 10, 64)        0         \n",
            "_________________________________________________________________\n",
            "batch_normalization_3 (Batch (None, 10, 10, 64)        256       \n",
            "_________________________________________________________________\n",
            "conv2d_5 (Conv2D)            (None, 5, 5, 64)          36928     \n",
            "_________________________________________________________________\n",
            "activation_4 (Activation)    (None, 5, 5, 64)          0         \n",
            "_________________________________________________________________\n",
            "batch_normalization_4 (Batch (None, 5, 5, 64)          256       \n",
            "_________________________________________________________________\n",
            "dropout_2 (Dropout)          (None, 5, 5, 64)          0         \n",
            "_________________________________________________________________\n",
            "conv2d_6 (Conv2D)            (None, 3, 3, 128)         73856     \n",
            "_________________________________________________________________\n",
            "activation_5 (Activation)    (None, 3, 3, 128)         0         \n",
            "_________________________________________________________________\n",
            "batch_normalization_5 (Batch (None, 3, 3, 128)         512       \n",
            "_________________________________________________________________\n",
            "conv2d_7 (Conv2D)            (None, 2, 2, 128)         147584    \n",
            "_________________________________________________________________\n",
            "activation_6 (Activation)    (None, 2, 2, 128)         0         \n",
            "_________________________________________________________________\n",
            "batch_normalization_6 (Batch (None, 2, 2, 128)         512       \n",
            "_________________________________________________________________\n",
            "dropout_3 (Dropout)          (None, 2, 2, 128)         0         \n",
            "_________________________________________________________________\n",
            "flatten_1 (Flatten)          (None, 512)               0         \n",
            "_________________________________________________________________\n",
            "dense_1 (Dense)              (None, 512)               262656    \n",
            "_________________________________________________________________\n",
            "activation_7 (Activation)    (None, 512)               0         \n",
            "_________________________________________________________________\n",
            "batch_normalization_7 (Batch (None, 512)               2048      \n",
            "_________________________________________________________________\n",
            "dropout_4 (Dropout)          (None, 512)               0         \n",
            "_________________________________________________________________\n",
            "dense_2 (Dense)              (None, 1)                 513       \n",
            "_________________________________________________________________\n",
            "activation_8 (Activation)    (None, 1)                 0         \n",
            "=================================================================\n",
            "Total params: 558,561\n",
            "Trainable params: 556,641\n",
            "Non-trainable params: 1,920\n",
            "_________________________________________________________________\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "5w1NPR7rEOG4",
        "colab_type": "code",
        "outputId": "d4101bab-6e8a-4cee-99ee-01fc94f26241",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        }
      },
      "source": [
        "# train the network\n",
        "print(\"[INFO] training network for {} epochs...\".format(epo))\n",
        "H = model.fit_generator(aug.flow(trainX, trainY, batch_size=32),\n",
        "\tvalidation_data=(testX, testY), steps_per_epoch=len(trainX) // 32,\n",
        "\tepochs=60)"
      ],
      "execution_count": 0,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "[INFO] training network for 60 epochs...\n",
            "Epoch 1/60\n",
            "393/393 [==============================] - 133s 337ms/step - loss: 9.5827 - accuracy: 0.3936 - val_loss: 9.4143 - val_accuracy: 0.3935\n",
            "Epoch 2/60\n",
            "393/393 [==============================] - 132s 335ms/step - loss: 9.4059 - accuracy: 0.3936 - val_loss: 9.3128 - val_accuracy: 0.3935\n",
            "Epoch 3/60\n",
            "393/393 [==============================] - 132s 335ms/step - loss: 9.3336 - accuracy: 0.3940 - val_loss: 9.2756 - val_accuracy: 0.3935\n",
            "Epoch 4/60\n",
            "393/393 [==============================] - 132s 335ms/step - loss: 9.3266 - accuracy: 0.3929 - val_loss: 9.2610 - val_accuracy: 0.3935\n",
            "Epoch 5/60\n",
            "393/393 [==============================] - 131s 334ms/step - loss: 9.2937 - accuracy: 0.3943 - val_loss: 9.2548 - val_accuracy: 0.3935\n",
            "Epoch 6/60\n",
            "393/393 [==============================] - 132s 337ms/step - loss: 9.3150 - accuracy: 0.3929 - val_loss: 9.2519 - val_accuracy: 0.3935\n",
            "Epoch 7/60\n",
            "393/393 [==============================] - 133s 338ms/step - loss: 9.2873 - accuracy: 0.3945 - val_loss: 9.2504 - val_accuracy: 0.3935\n",
            "Epoch 8/60\n",
            "393/393 [==============================] - 133s 339ms/step - loss: 9.3081 - accuracy: 0.3928 - val_loss: 9.2496 - val_accuracy: 0.3935\n",
            "Epoch 9/60\n",
            "393/393 [==============================] - 132s 337ms/step - loss: 9.2916 - accuracy: 0.3939 - val_loss: 9.2491 - val_accuracy: 0.3935\n",
            "Epoch 10/60\n",
            "393/393 [==============================] - 133s 338ms/step - loss: 9.3156 - accuracy: 0.3927 - val_loss: 9.2488 - val_accuracy: 0.3935\n",
            "Epoch 11/60\n",
            "393/393 [==============================] - 133s 338ms/step - loss: 9.2800 - accuracy: 0.3947 - val_loss: 9.2486 - val_accuracy: 0.3935\n",
            "Epoch 12/60\n",
            "393/393 [==============================] - 133s 337ms/step - loss: 9.2945 - accuracy: 0.3937 - val_loss: 9.2485 - val_accuracy: 0.3935\n",
            "Epoch 13/60\n",
            "393/393 [==============================] - 131s 334ms/step - loss: 9.3164 - accuracy: 0.3925 - val_loss: 9.2484 - val_accuracy: 0.3935\n",
            "Epoch 14/60\n",
            "393/393 [==============================] - 131s 333ms/step - loss: 9.2980 - accuracy: 0.3936 - val_loss: 9.2484 - val_accuracy: 0.3935\n",
            "Epoch 15/60\n",
            "393/393 [==============================] - 132s 337ms/step - loss: 9.3029 - accuracy: 0.3933 - val_loss: 9.2484 - val_accuracy: 0.3935\n",
            "Epoch 16/60\n",
            "393/393 [==============================] - 133s 338ms/step - loss: 9.2968 - accuracy: 0.3936 - val_loss: 9.2484 - val_accuracy: 0.3935\n",
            "Epoch 17/60\n",
            "393/393 [==============================] - 133s 337ms/step - loss: 9.2712 - accuracy: 0.3952 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 18/60\n",
            "393/393 [==============================] - 132s 335ms/step - loss: 9.3114 - accuracy: 0.3928 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 19/60\n",
            "393/393 [==============================] - 133s 338ms/step - loss: 9.3053 - accuracy: 0.3932 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 20/60\n",
            "393/393 [==============================] - 132s 337ms/step - loss: 9.3102 - accuracy: 0.3929 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 21/60\n",
            "393/393 [==============================] - 133s 338ms/step - loss: 9.2943 - accuracy: 0.3939 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 22/60\n",
            "393/393 [==============================] - 133s 339ms/step - loss: 9.2882 - accuracy: 0.3943 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 23/60\n",
            "393/393 [==============================] - 133s 339ms/step - loss: 9.3187 - accuracy: 0.3921 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 24/60\n",
            "393/393 [==============================] - 132s 336ms/step - loss: 9.2968 - accuracy: 0.3935 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 25/60\n",
            "393/393 [==============================] - 133s 338ms/step - loss: 9.2870 - accuracy: 0.3943 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 26/60\n",
            "393/393 [==============================] - 134s 340ms/step - loss: 9.3065 - accuracy: 0.3928 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 27/60\n",
            "393/393 [==============================] - 133s 339ms/step - loss: 9.2785 - accuracy: 0.3947 - val_loss: 9.2483 - val_accuracy: 0.3935\n",
            "Epoch 28/60\n",
            "315/393 [=======================>......] - ETA: 24s - loss: 9.3247 - accuracy: 0.3919"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "xBS1TbX3luJh",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        "print(\"[INFO] evaluating network...\")\n",
        "predictions = model.predict(testX, batch_size=32)\n",
        "print(classification_report(testY.argmax(axis=1),\n",
        "\tpredictions.argmax(axis=1), target_names=lb.classes_))"
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "HRilRML9mAQG",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        ""
      ],
      "execution_count": 0,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "HFIbq8qilvCn",
        "colab_type": "code",
        "colab": {}
      },
      "source": [
        ""
      ],
      "execution_count": 0,
      "outputs": []
    }
  ]
}